baseURL = 'https://laurenceputra.github.io/'
languageCode = 'en-us'
title = 'Laurence Putra Franslay'
theme = 'laurenceputra'

[params]
  description = "Tech Leader, Philanthropist & Social Fixer"
  author = "Laurence Putra Franslay"
  twitter = "laurenceputra"
  github = "laurenceputra"
  flickr = "laurenceputra"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

# Disable taxonomy pages we don't need
[build]
  writeStats = false

disableKinds = ["taxonomy", "term"]
